# -*- coding: utf-8 -*-
"""Trabajo_final_InteligenciaArtificial.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ULjPz6MVtCqepHJQQQdZRffLZaoP369c

##Sistema Inteligente para la Gestión de Solicitudes de Soporte Técnico (AI Elite, S.R.L.)
Este **proyecto** presenta el desarrollo de un **prototipo inteligente** para la empresa ficticia **AI Elite**, S.R.L., orientado a optimizar la **gestión de solicitudes** de soporte técnico mediante técnicas de **inteligencia artificial** y **aprendizaje automático**. A lo largo del proyecto se implementan diferentes funcionalidades que permiten **automatizar procesos** que tradicionalmente se realizan de forma manual, con el propósito de mejorar la eficiencia en la atención de los usuarios, facilitar la toma de decisiones y reducir los tiempos de respuesta.

Además, el proyecto integra herramientas de **análisis de datos**, un agente inteligente, un chatbot de orientación inicial y un modelo de **Machine Learning** capaz de predecir la prioridad de los casos a partir de la información registrada.
"""

# Llamada de las librerias de forma general
from google.colab import drive
import os
import pandas as pd
import sklearn
from datetime import datetime
import matplotlib.pyplot as plt
import numpy as np

# El dataset se encuentra alojado en github como todo el codigo para que el facilitador Edwin Aponte pueda usar mi sistema en su maquina
ruta_dataset = "https://raw.githubusercontent.com/franyely23/AI-ELITE-/refs/heads/main/solicitudes_soporte_ia.csv"
dataset = pd.read_csv(ruta_dataset)

# Mostramos las primeras 5 líneas de forma visual en la celda
display(dataset.head(5))

"""**Información general del dataset**



> Muestra un resumen estructural del dataset mediante un gráfico de barras.




"""

def mostrar_resumen_dataset(dataset):

# Validar que el dataset contenga información
    if dataset.empty:
        print("El dataset está vacío.")
        return

    # Obtener métricas generales del dataset
    cantidad_registros = dataset.shape[0]

    cantidad_columnas = dataset.shape[1]

    columnas_disponibles = list(dataset.columns)

    valores_faltantes = dataset.isnull().sum().sum()

    duplicados = dataset.duplicated().sum()

    variables_numericas = dataset.select_dtypes(include="number").shape[1]

    variables_categoricas = dataset.select_dtypes(exclude="number").shape[1]

    porcentaje_faltantes = (

        valores_faltantes /
        (cantidad_registros * cantidad_columnas)
    ) * 100

    # Información de el gráfico
    categorias = [
        "Registros",
        "Columnas",
        "Valores\nFaltantes",
        "Duplicados"
    ]

    valores = [
        cantidad_registros,
        cantidad_columnas,
        valores_faltantes,
        duplicados
    ]


    # Configuración
    plt.style.use("seaborn-v0_8-whitegrid")
    fig, ax = plt.subplots(figsize=(12, 7))
    barras = ax.bar(
        categorias,
        valores,
        color=[
            "#4E79A7",
            "#59A14F",
            "#E15759",
            "#F28E2B"
        ],
        edgecolor="black",
        linewidth=0.8
    )

    if len(columnas_disponibles) <= 8:

        columnas_formateadas = ", ".join(columnas_disponibles)

    else:

        columnas_formateadas = (
            ", ".join(columnas_disponibles[:8])
            + f"... (+{len(columnas_disponibles)-8} columnas)"
        )

    ax.set_title(
        "Resumen Estructural del Dataset\n"
        f"Columnas: {columnas_formateadas}",
        fontsize=13,
        fontweight="bold",
        pad=20
    )

    ax.set_ylabel(
        "Cantidad",
        fontsize=12,
        fontweight="bold"
    )

    ax.set_xlabel(
        "Métricas Analizadas",
        fontsize=12,
        fontweight="bold"
    )


    valor_maximo = max(valores)

    if valor_maximo == 0:
        valor_maximo = 10

    ax.set_ylim(0, valor_maximo * 1.20)

    for i, barra in enumerate(barras):

        altura = barra.get_height()

        if categorias[i] == "Valores\nFaltantes":

            texto = (
                f"{int(altura)}\n"
                f"({porcentaje_faltantes:.2f}%)"
            )

        else:

            texto = f"{int(altura)}"

        ax.annotate(
            texto,
            xy=(
                barra.get_x() + barra.get_width() / 2,
                altura
            ),
            xytext=(0, 5),
            textcoords="offset points",
            ha="center",
            va="bottom",
            fontsize=10,
            fontweight="bold"
        )

    ax.legend(
        barras,
        [
            "Volumen",
            "Dimensiones",
            "Integridad",
            "Calidad"
        ],
        title="Indicadores",
        loc="upper right",
        frameon=True
    )

    #Resumen debajo del gráfico

    resumen = (
        f"Variables Numéricas : {variables_numericas}\n"
        f"Variables Categóricas : {variables_categoricas}\n"
        f"Registros Duplicados : {duplicados}\n"
        f"Valores Faltantes : {valores_faltantes} ({porcentaje_faltantes:.2f}%)"
    )

    plt.figtext(
        0.02,
        -0.06,
        resumen,
        fontsize=10,
        bbox=dict(
            facecolor="#F5F5F5",
            edgecolor="gray",
            boxstyle="round"
        )
    )

    plt.tight_layout()

    plt.show()

# llamada a la funsion para mostrar un grafico de un resumen del dataset
mostrar_resumen_dataset(dataset)

"""**Información especifica del dataset**

>Representa el analisis de la distribución de las solicitudes de soporte registradas en el dataset. Cada gráfico muestra cuántos tickets existen según un criterio diferente, facilitando la identificación de tendencias y patrones.


"""

def mostrar_patrones_dataset(dataset):

    # 1. CONFIGURACIÓN DE COLUMNAS
    COL_CATEGORIA = "categoria"
    COL_URGENCIA = "urgencia"
    COL_AREA = "area"
    COL_PRIORIDAD = "prioridad"

    plt.style.use("seaborn-v0_8-whitegrid")

    fig, ejes = plt.subplots(2, 2, figsize=(16, 12))
    ((ax1, ax2), (ax3, ax4)) = ejes

    # GRÁFICO 1: Cantidad de solicitudes por categoría
    conteo_categoria = dataset[COL_CATEGORIA].value_counts()

    ax1.bar(
        conteo_categoria.index,
        conteo_categoria.values,
        color="#4E79A7",
        edgecolor="black",
        linewidth=0.8,
    )

    ax1.set_title(
        "Cantidad de Solicitudes por Categoría",
        fontsize=12,
        fontweight="bold",
    )

    ax1.set_ylabel("Total de Solicitudes")
    ax1.tick_params(axis="x", rotation=15)

    for i, valor in enumerate(conteo_categoria.values):
        ax1.text(
            i,
            valor + (valor * 0.02),
            str(valor),
            ha="center",
            fontweight="bold",
        )

    # GRÁFICO 2: Cantidad de solicitudes por urgencia
    conteo_urgencia = dataset[COL_URGENCIA].value_counts()

    ax2.bar(
        conteo_urgencia.index,
        conteo_urgencia.values,
        color="#E15759",
        edgecolor="black",
        linewidth=0.8,
    )

    ax2.set_title(
        "Cantidad de Solicitudes por Urgencia",
        fontsize=12,
        fontweight="bold",
    )

    ax2.set_ylabel("Total de Solicitudes")

    for i, valor in enumerate(conteo_urgencia.values):
        ax2.text(
            i,
            valor + (valor * 0.02),
            str(valor),
            ha="center",
            fontweight="bold",
        )

    # GRÁFICO 3: Cantidad de solicitudes por área afectada
    conteo_areas = dataset[COL_AREA].value_counts()

    ax3.bar(
        conteo_areas.index,
        conteo_areas.values,
        color="#59A14F",
        edgecolor="black",
        linewidth=0.8,
    )

    ax3.set_title(
        "Cantidad de Solicitudes por Área Afectada",
        fontsize=12,
        fontweight="bold",
    )

    ax3.set_ylabel("Total de Solicitudes")
    ax3.tick_params(axis="x", rotation=15)

    for i, valor in enumerate(conteo_areas.values):
        ax3.text(
            i,
            valor + (valor * 0.02),
            str(valor),
            ha="center",
            fontweight="bold",
        )

    # GRÁFICO 4: Cantidad de solicitudes por prioridad
    conteo_prioridad = dataset[COL_PRIORIDAD].value_counts()

    ax4.bar(
        conteo_prioridad.index,
        conteo_prioridad.values,
        color="#F28E2B",
        edgecolor="black",
        linewidth=0.8,
    )

    ax4.set_title(
        "Cantidad de Solicitudes por Prioridad",
        fontsize=12,
        fontweight="bold",
    )

    ax4.set_ylabel("Total de Solicitudes")

    for i, valor in enumerate(conteo_prioridad.values):
        ax4.text(
            i,
            valor + (valor * 0.02),
            str(valor),
            ha="center",
            fontweight="bold",
        )

    plt.tight_layout()
    plt.show()

# llamada a la funsion para mostrar un grafico de identificacion de patrones del dataset
mostrar_patrones_dataset(dataset)

"""**Funsion buscar ticket**

>Solicita un número de ticket, valida la entrada, busca el ticket en el dataset y muestra su información si existe; permite salir al menú principal.


"""

def buscar_tickets():
    while True:
        numero = input("\nIngrese el número de ticket a buscar (o escribe 'salir' para volver): ")

        if numero.lower() == 'salir' or numero == '6':
            print("\nRegresando al menú principal...")
            break

        # Validamos si la entrada es numérica
        if not numero.isdigit():
            print(f"Error de entrada: '{numero}' contiene letras o caracteres no válidos.")
            print("Por favor, introduce solo dígitos numéricos (ej. 1001). Inténtalo de nuevo.")
            continue

        # Si pasó la validación, lo convertimos con a entero
        numero_ticket = int(numero)

        # Búsqueda en el dataset
        coincidencia = dataset[dataset['ticket'] == numero_ticket]

        # Verificamos si encontramos el ticket
        if not coincidencia.empty:
            print("\n" + "="*40)
            print(f"INFORMACIÓN DEL TICKET: {numero_ticket}")
            print("="*40)

            ticket_datos = coincidencia.iloc[0]
            for clave, valor in ticket_datos.items():
                # Saltamos la columna 'ticket' para no repetirla en el reporte
                if clave == 'ticket':
                    continue

                # Formateamos el nombre de las columnas (cambiamos '_' por espacios y capitalizamos)
                columna_formateada = str(clave).replace('_', ' ').capitalize()
                print(f"{columna_formateada:<22}: {valor}")

            print("="*40)
            break

        else:
            print(f"Buscado: Ticket {numero_ticket} No encontrado en el sistema. Inténtalo de nuevo.")

"""**Recomendacion al usuario**


>Sistema basado en reglas que recomienda una acción inicial al usuario según la categoría del incidente y el dispositivo utilizado.
   


"""

def recomendar_accion_inicial_usuario(categoria, dispositivo):

    cat = str(categoria).strip().lower()
    disp = str(dispositivo).strip().lower()

    # ACCESO AL SISTEMA

    if ("acceso" in cat or
        "login" in cat or
        "contraseña" in cat or
        "autenticación" in cat):

        return (
            "Verifique que esté escribiendo correctamente su usuario y contraseña. "
            "Si olvidó la contraseña, utilice la opción 'Restablecer contraseña'. "
            "Si el problema continúa, intente ingresar desde otro navegador o una "
            "ventana de incógnito."
        )

    # CORREO ELECTRÓNICO

    elif ("correo" in cat or
          "email" in cat or
          "outlook" in cat or
          "gmail" in cat):

        return (
            "Compruebe que tenga conexión a Internet. Revise la carpeta de spam "
            "o correo no deseado. Cierre sesión e ingrese nuevamente. "
            "Si utiliza Outlook, sincronice el buzón y verifique que no esté lleno."
        )

    # INTERNET

    elif ("internet" in cat or
          "wifi" in cat or
          "red" in cat):

        return (
            "Revise que el cable de red esté conectado o que el Wi-Fi esté activado. "
            "Reinicie el router o vuelva a conectarse a la red inalámbrica. "
            "Si otros dispositivos tampoco tienen Internet, reporte la falla."
        )

    # IMPRESORA

    elif ("impresora" in cat or
          "impresión" in cat):

        return (
            "Verifique que la impresora esté encendida y conectada. "
            "Confirme que tenga papel y tinta o tóner. "
            "Revise la cola de impresión y elimine documentos atascados si es necesario."
        )
    # EQUIPO LENTO

    elif ("lento" in cat or
          "rendimiento" in cat or
          "equipo" in cat):

        if ("celular" in disp or
            "movil" in disp or
            "móvil" in disp or
            "telefono" in disp or
            "teléfono" in disp):

            return (
                "Cierre las aplicaciones abiertas, elimine archivos innecesarios, "
                "libere espacio de almacenamiento y reinicie el dispositivo."
            )

        else:
            return (
                "Reinicie el equipo, cierre programas que no esté utilizando, "
                "libere espacio en disco y espere unos minutos después del inicio "
                "para que finalicen las actualizaciones automáticas."
            )

    # BASE DE DATOS

    elif ("base de datos" in cat or
          "bd" in cat):

        return (
            "Actualice la página e intente nuevamente. "
            "Si aparece un código de error, tome una captura de pantalla y envíela "
            "al departamento de soporte para agilizar el diagnóstico."
        )

    # PLATAFORMA VIRTUAL

    elif ("plataforma" in cat or
          "virtual" in cat or
          "campus" in cat):

        return (
            "Borre la memoria caché del navegador, intente acceder desde Google Chrome "
            "o Microsoft Edge actualizado y pruebe desde otro navegador si el problema continúa."
        )

    # SOFTWARE

    elif ("software" in cat or
          "programa" in cat or
          "aplicación" in cat or
          "aplicacion" in cat):

        return (
            "Cierre completamente la aplicación y vuelva a abrirla. "
            "Compruebe si existe una actualización disponible y reinicie el equipo "
            "antes de volver a intentarlo."
        )

    # HARDWARE

    elif ("hardware" in cat or
          "monitor" in cat or
          "teclado" in cat or
          "mouse" in cat or
          "pantalla" in cat):

        return (
            "Verifique que todos los cables estén correctamente conectados. "
            "Desconecte y vuelva a conectar el dispositivo. "
            "Si el problema persiste, no manipule el equipo y espere la revisión técnica."
        )

    # SEGURIDAD

    elif ("seguridad" in cat or
          "virus" in cat or
          "malware" in cat or
          "phishing" in cat):

        return (
            "Desconecte el equipo de Internet si sospecha de una infección. "
            "No abra enlaces ni archivos sospechosos. "
            "Ejecute un análisis con el antivirus y comunique inmediatamente el incidente."
        )

    # CASO GENERAL

    else:
        return (
            "Reinicie el equipo o dispositivo e intente nuevamente. "
            "Verifique que tenga conexión a Internet y que esté utilizando un navegador actualizado. "
            "Si el problema continúa, registre una captura de pantalla y describa el mensaje de error."
        )

"""**Recomendacion al equipo de soporte**

>Determina la acción inicial de soporte según la categoría, urgencia e impacto del incidente.


"""

def recomendar_accion_inicial_soporte(categoria, urgencia, impacto):

    cat = str(categoria).lower().strip()
    urg = str(urgencia).lower().strip()
    imp = str(impacto).lower().strip()

    #INCIDENTES CRÍTICOS

    if "seguridad" in cat:
        return (
            "Aislar inmediatamente el equipo afectado, escalar el incidente al "
            "responsable de seguridad informática y documentar todas las acciones realizadas."
        )

    if "base de datos" in cat:
        return (
            "Escalar al administrador de bases de datos (DBA), revisar los servicios "
            "del servidor y verificar la disponibilidad de respaldos."
        )

    if "internet" in cat:
        return (
            "Verificar conectividad local, switches, router y proveedor de Internet "
            "antes de asignar el incidente a redes."
        )

    if "acceso" in cat:
        return (
            "Validar la identidad del usuario, comprobar permisos y revisar el "
            "servidor de autenticación."
        )

    if "correo" in cat:
        return (
            "Revisar el estado del servidor de correo, validar credenciales y "
            "comprobar la capacidad del buzón."
        )

    if "plataforma" in cat:
        return (
            "Comprobar disponibilidad del servidor de la plataforma educativa y "
            "revisar los registros (logs) de errores."
        )

    if "hardware" in cat:
        return (
            "Programar revisión física del equipo y determinar si requiere "
            "reemplazo de componentes."
        )

    if "software" in cat:
        return (
            "Verificar versión instalada, licencias y registros de errores antes "
            "de reinstalar la aplicación."
        )

    if "impresora" in cat:
        return (
            "Comprobar estado físico de la impresora, conectividad y cola de impresión."
        )

    if "equipo lento" in cat:
        return (
            "Revisar consumo de CPU, memoria y almacenamiento; ejecutar diagnóstico "
            "de rendimiento y análisis antivirus."
        )

    #PRIORIZACIÓN GENERAL

    if urg == "alta" and imp == "alto":
        return (
            "Escalar inmediatamente al soporte de segundo nivel y comenzar el "
            "diagnóstico en menos de 30 minutos."
        )

    elif urg == "alta":
        return (
            "Asignar al primer técnico disponible para atención prioritaria."
        )

    elif urg == "media":
        return (
            "Asignar a la cola normal de soporte para resolución durante la jornada."
        )

    elif urg == "baja":
        return (
            "Programar la atención según disponibilidad del equipo técnico."
        )

    return (
        "Registrar el incidente y enviarlo a Mesa de Ayuda para clasificación manual."
    )

"""**Entrenamiento del machine learning**



>Prepara los datos, codifica las variables categóricas, entrena dos árboles de decisión (prioridad y tiempo estimado) y evalúa su rendimiento.


"""

#COLUMNAS QUE UTILIZARÁ EL MODELO
columnas_entrenamiento = [
    "categoria",
    "area",
    "urgencia",
    "impacto",
    "tiempo_estimado_min",
    "canal",
    "tipo_usuario",
    "dispositivo",
    "horario",
    "prioridad",
]

# Eliminamos filas con valores nulos para evitar errores durante el entrenamiento
datos_entrenamiento = dataset[columnas_entrenamiento].dropna().copy()

#CODIFICACIÓN DE VARIABLES CATEGÓRICAS
codificadores = {}

columnas_categoricas = [
    "categoria",
    "area",
    "urgencia",
    "impacto",
    "canal",
    "tipo_usuario",
    "dispositivo",
    "horario",
]

for nombre_columna in columnas_categoricas:

    codificador = sklearn.preprocessing.LabelEncoder()

    datos_entrenamiento[nombre_columna] = codificador.fit_transform(
        datos_entrenamiento[nombre_columna].astype(str)
    )

    codificadores[nombre_columna] = codificador

#VARIABLES DE ENTRADA (X)
variables_entrada = datos_entrenamiento[columnas_categoricas]

#VARIABLES OBJETIVO (Y)
objetivo_prioridad = dataset.loc[
    datos_entrenamiento.index,
    "prioridad",
]

objetivo_tiempo = datos_entrenamiento["tiempo_estimado_min"]


#DIVISIÓN DE DATOS Y ENTRENAMIENTO DEL MODELO DE PRIORIDAD
(
    X_entrenamiento_prioridad,
    X_prueba_prioridad,
    y_entrenamiento_prioridad,
    y_prueba_prioridad,
) = sklearn.model_selection.train_test_split(
    variables_entrada,
    objetivo_prioridad,
    test_size=0.20,
    random_state=42,
)

modelo_prioridad = sklearn.tree.DecisionTreeClassifier(
    random_state=42,
    max_depth=6,
)

modelo_prioridad.fit(
    X_entrenamiento_prioridad,
    y_entrenamiento_prioridad,
)

#DIVISIÓN DE DATOS Y ENTRENAMIENTO DEL MODELO DE TIEMPO
(
    X_entrenamiento_tiempo,
    X_prueba_tiempo,
    y_entrenamiento_tiempo,
    y_prueba_tiempo,
) = sklearn.model_selection.train_test_split(
    variables_entrada,
    objetivo_tiempo,
    test_size=0.20,
    random_state=42,
)

modelo_tiempo = sklearn.tree.DecisionTreeRegressor(
    random_state=42,
    max_depth=6,
)

modelo_tiempo.fit(
    X_entrenamiento_tiempo,
    y_entrenamiento_tiempo,
)

"""**Funsion chatbot**

> Chatbot básico de orientación inicial que interactúa con el usuario


"""

def iniciar_chatbot():

    print("\n" + "=" * 70)
    print("🤖 ASISTENTE AI ÉLITE")
    print("=" * 70)
    print("¡Hola! Soy tu asistente virtual de soporte técnico.\n")
    print("Puedo ayudarte a:")
    print(" • Registrar un ticket de soporte.")
    print(" • Buscar un ticket existente.")
    print(" • Mostrar las primeras 5 filas del dataset.")
    print(" • Mostrar un resumen del dataset.")
    print(" • Analizar patrones del dataset.")
    print(" • Orientarte sobre un problema técnico.")
    print(" • Recomendar la acción inicial de soporte.")
    print("\nEscribe 'salir' para regresar al menú principal.")
    print("=" * 70)

    while True:

        peticion = input("\n👤 Tú: ").strip().lower()

        if peticion == "salir":
            print("\n🤖 [Asistente AI Élite]: Regresando al menú principal...\n")
            break

        if peticion == "":
            print("🤖 [Asistente AI Élite]: Por favor escribe tu consulta.")
            continue

        # MOSTRAR DATASET

        if (
            "dataset" in peticion
            or "datos" in peticion
            or "head" in peticion
            or "primeras filas" in peticion
            or "mostrar dataset" in peticion
        ):

            print("\nPrimeras 5 filas del dataset:\n")
            display(dataset.head(5))
            continue

        # RESUMEN DATASET

        if (
            "resumen" in peticion
            or "estadisticas" in peticion
            or "estadística" in peticion
            or "estadisticas del dataset" in peticion
        ):

            print("\nGenerando resumen...\n")
            mostrar_resumen_dataset(dataset)
            continue

        # PATRONES

        if (
            "patrones" in peticion
            or "analisis" in peticion
            or "análisis" in peticion
            or "comportamiento" in peticion
        ):

            print("\nAnalizando patrones del dataset...\n")
            mostrar_patrones_dataset(dataset)
            continue

        # BUSCAR TICKET

        if (
            ("buscar" in peticion or "consultar" in peticion)
            and "ticket" in peticion
        ):

            buscar_tickets()
            continue

        # REGISTRAR TICKET

        if (
            "registrar" in peticion
            or "crear ticket" in peticion
            or "nuevo ticket" in peticion
        ):

            print("\nRegistro de nuevo ticket\n")

            categoria = input("Categoría: ")
            area = input("Área: ")
            tipo_usuario = input("Tipo de usuario: ")
            dispositivo = input("Dispositivo: ")
            urgencia = input("Urgencia (Alta/Media/Baja): ")
            impacto = input("Impacto (Alto/Medio/Bajo): ")
            descripcion = input("Descripción: ")

            accion = recomendar_accion_inicial_soporte(
                categoria,
                urgencia,
                impacto,
            )

            print("\nAcción inicial recomendada:")
            print(accion)

            registrar_ticket(
                categoria,
                area,
                tipo_usuario,
                dispositivo,
                urgencia,
                impacto,
                descripcion,
            )

            print("\nTicket registrado correctamente.")
            continue

        # ORIENTACIÓN AUTOMÁTICA

        categoria = "Infraestructura"

        if any(
            palabra in peticion
            for palabra in [
                "acceso",
                "entrar",
                "login",
                "usuario",
                "contraseña",
                "clave",
                "credenciales",
            ]
        ):

            categoria = "Accesos"

            print("\nDetecté un problema de acceso.")
            print("Sugerencias:")
            print("- Verifica usuario y contraseña.")
            print("- Borra la caché del navegador.")
            print("- Intenta iniciar sesión en modo incógnito.")

        elif any(
            palabra in peticion
            for palabra in [
                "correo",
                "email",
                "outlook",
                "gmail",
            ]
        ):

            categoria = "Correo"

            print("\nParece un problema relacionado con el correo.")
            print("- Verifica las credenciales.")
            print("- Comprueba el espacio disponible del buzón.")
            print("- Revisa tu conexión a Internet.")

        elif any(
            palabra in peticion
            for palabra in [
                "internet",
                "wifi",
                "red",
                "conexion",
                "conexión",
            ]
        ):

            categoria = "Internet"

            print("\nDetecté un problema de conectividad.")
            print("- Reinicia el router.")
            print("- Comprueba el cable de red.")
            print("- Verifica si otros equipos tienen conexión.")

        elif any(
            palabra in peticion
            for palabra in [
                "lento",
                "lenta",
                "pc",
                "computadora",
                "equipo",
                "rendimiento",
            ]
        ):

            categoria = "Equipo lento"

            print("\nParece un problema de rendimiento.")
            print("- Reinicia el equipo.")
            print("- Cierra programas innecesarios.")
            print("- Ejecuta un análisis antivirus.")

        elif any(
            palabra in peticion
            for palabra in [
                "software",
                "programa",
                "aplicacion",
                "aplicación",
                "error",
                "sistema",
                "plataforma",
            ]
        ):

            categoria = "Software"

            print("\nDetecté un problema relacionado con software.")
            print("- Reinicia la aplicación.")
            print("- Comprueba si hay actualizaciones.")
            print("- Verifica la conexión al servidor.")

        elif any(
            palabra in peticion
            for palabra in [
                "impresora",
                "imprimir",
                "impresión",
            ]
        ):

            categoria = "Impresora"

            print("\nDetecté un problema con la impresora.")
            print("- Comprueba la cola de impresión.")
            print("- Verifica la conexión.")
            print("- Reinicia la impresora.")

        elif any(
            palabra in peticion
            for palabra in [
                "base de datos",
                "sql",
                "mysql",
                "postgres",
            ]
        ):

            categoria = "Base de Datos"

            print("\nParece un problema relacionado con la base de datos.")
            print("- Comprueba que el servicio esté iniciado.")
            print("- Revisa los registros del servidor.")

        elif any(
            palabra in peticion
            for palabra in [
                "virus",
                "hack",
                "seguridad",
                "malware",
                "ransomware",
            ]
        ):

            categoria = "Seguridad"

            print("\nPosible incidente de seguridad.")
            print("- Desconecta el equipo de la red.")
            print("- No elimines evidencia.")
            print("- Informa inmediatamente al administrador.")

        else:

            print("\n🤖 Entiendo tu consulta.")
            print("Haré una orientación general.")

        print("\n¿La orientación resolvió tu problema? (si/no)")
        respuesta = input("👤 Tú: ").strip().lower()

        if respuesta == "si":

            print("\n¡Excelente! Me alegra haber podido ayudarte.")
            continue

        print("\nProcederemos a registrar un ticket.\n")

        area = input("Área: ")
        tipo_usuario = input("Tipo de usuario: ")
        dispositivo = input("Dispositivo: ")
        urgencia = input("Urgencia (Alta/Media/Baja): ")
        impacto = input("Impacto (Alto/Medio/Bajo): ")

        accion = recomendar_accion_inicial_soporte(
            categoria,
            urgencia,
            impacto,
        )

        print("\nAcción inicial recomendada:")
        print(accion)

        registrar_ticket(
            categoria,
            area,
            tipo_usuario,
            dispositivo,
            urgencia,
            impacto,
            peticion,
        )

        print("\El ticket ha sido registrado correctamente.")
        print("¿Hay algo más en lo que pueda ayudarte?")

"""

> Funsion para la visualizar las opciones, guiar el usuario y  optener datos para registrar tickets


"""

def seleccionar_opcion(titulo, opciones):

    print("\n" + "-" * 50)
    print(titulo)
    print("-" * 50)

    print("0. ← Volver al paso anterior")

    for i, opcion in enumerate(opciones, start=1):
        print(f"{i}. {opcion}")

    while True:
        try:
            seleccion = int(input("\nSeleccione una opción: "))

            if seleccion == 0:
                return "VOLVER"

            if 1 <= seleccion <= len(opciones):
                return opciones[seleccion - 1]

            print("Opción fuera de rango. Intente nuevamente.")

        except ValueError:
            print("Debe ingresar un número.")

"""**Fusion de ingresar ticket**

> Registra un nuevo ticket de soporte técnico, calcula automáticamente su prioridad y tiempo estimado mediante inteligencia artificial, genera recomendaciones iniciales y guarda el caso en el dataset.






"""

def registrar_ticket(categoria, area, tipo_usuario, dispositivo, urgencia,impacto,descripcion,):
    global dataset

# CONFIGURACIÓN DE CREDENCIALES DE GITHUB
    GITHUB_TOKEN = "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"
    GITHUB_USER = "franyely23"
    GITHUB_REPO = "AI-ELITE-"

# VALIDACIÓN DE DATOS
    try:

        campos_obligatorios = {
            "Categoría": categoria,
            "Área": area,
            "Tipo de usuario": tipo_usuario,
            "Dispositivo": dispositivo,
            "Urgencia": urgencia,
            "Impacto": impacto,
            "Descripción": descripcion,
        }

        campos_vacios = [
            nombre
            for nombre, valor in campos_obligatorios.items()
            if not str(valor).strip()
        ]

        if campos_vacios:
            print(
                "Error: Los siguientes campos son obligatorios:\n- "
                + "\n- ".join(campos_vacios)
            )
            return

        # 2. GENERAR EL NÚMERO DEL TICKET

        if dataset.empty:

            nuevo_ticket = 1

        else:

            numeros_ticket = pd.to_numeric(
                dataset["ticket"],
                errors="coerce",
            )

            nuevo_ticket = int(numeros_ticket.max()) + 1


        #CALCULAR FECHA Y HORARIO

        fecha_hora_actual = datetime.now()

        fecha_reporte = fecha_hora_actual.strftime("%Y-%m-%d")

        horario_registro = (
            "Laboral"
            if (
                fecha_hora_actual.weekday() < 5
                and 8 <= fecha_hora_actual.hour < 17
            )
            else "No laboral"
        )


        # NORMALIZAR DATOS

        canal_registro = "AI ELITE"

        dispositivo_normalizado = (
            str(dispositivo).strip()
            if str(dispositivo).strip()
            else "No especificado"
        )

        # PREPARAR LOS DATOS PARA EL MODELO
        datos_prediccion = {
            "categoria": categoria,
            "area": area,
            "urgencia": urgencia,
            "impacto": impacto,
            "canal": canal_registro,
            "tipo_usuario": tipo_usuario,
            "dispositivo": dispositivo_normalizado,
            "horario": horario_registro,
        }
        datos_modelo = pd.DataFrame([datos_prediccion])

        #CODIFICAR VARIABLES CATEGÓRICAS

        for nombre_columna in columnas_categoricas:

            if nombre_columna in codificadores:

                try:

                    datos_modelo[nombre_columna] = codificadores[
                        nombre_columna
                    ].transform(
                        datos_modelo[nombre_columna].astype(str)
                    )

                except ValueError:

                    # Valor desconocido para el modelo
                    datos_modelo[nombre_columna] = 0

        prioridad_calculada = modelo_prioridad.predict(
            datos_modelo
        )[0]

        tiempo_estimado = int(
            round(modelo_tiempo.predict(datos_modelo)[0])
        )

        # GENERAR RECOMENDACIONES

        accion_inicial_soporte = recomendar_accion_inicial_soporte(categoria, urgencia, impacto,)
        accion_inicial_usuario = recomendar_accion_inicial_usuario(categoria, dispositivo_normalizado,)

        #CREAR NUEVO REGISTRO

        nuevo_ticket_registrado = {
            "ticket": nuevo_ticket,
            "fecha_reporte": fecha_reporte,
            "categoria": categoria,
            "area": area,
            "urgencia": urgencia,
            "impacto": impacto,
            "tiempo_estimado_min": tiempo_estimado,
            "canal": canal_registro,
            "tipo_usuario": tipo_usuario,
            "dispositivo": dispositivo_normalizado,
            "horario": horario_registro,
            "prioridad": prioridad_calculada,
            "escalar": np.nan,
            "accion_recomendada": accion_inicial_soporte,
            "accion_sugerida": accion_inicial_usuario,
            "descripcion": descripcion,
        }

        dataset = pd.concat([dataset, pd.DataFrame([nuevo_ticket_registrado]),],ignore_index=True,)

        #GUARDAR EL DATASET

        print("\nSincronizando el nuevo ticket con el repositorio de GitHub...")
        nombre_archivo = "solicitudes_soporte_ia.csv"

        # Guardamos el archivo modificado localmente en la máquina virtual de Colab
        dataset.to_csv(nombre_archivo, index=False)

        # Ejecutamos la automatización de comandos de Git usando el Token de Seguridad
        if GITHUB_TOKEN != "TU_TOKEN_AQUÍ":
            # Configuración de identidad temporal de Git en Colab
            os.system('git config --global user.name "AI Elite Bot"')
            os.system('git config --global user.email "bot@aielite.com"')

            # Clonamos o inicializamos la conexión segura mediante la URL formateada con el Token
            url_remota_autenticada = f"https://{GITHUB_TOKEN}@github.com/{GITHUB_USER}/{GITHUB_REPO}.git"

            # Comandos de envío automatizados
            os.system('git init -b main')
            os.system(f'git remote remove origin 2>/dev/null')
            os.system(f'git remote add origin {url_remota_autenticada}')
            os.system(f'git add {nombre_archivo}')
            os.system(f'git commit -m "Registro automático: Ticket #{nuevo_ticket}"')

            # Forzamos la actualización en la rama principal en la nube
            resultado_push = os.system('git push -f origin main')

            if resultado_push == 0:
                print("¡Sincronización exitosa! El dataset se ha actualizado permanentemente en GitHub.")
            else:
                print("Alerta: No se pudo subir a GitHub. Verifica que tu Token sea correcto y no haya expirado.")
        else:
            print("Modo Demostración: El ticket se registró localmente pero no se subió a GitHub porque no has ingresado tu Token.")

    # RESUMEN DEL TICKET

        print("\n" + "=" * 60)
        print(f"TICKET #{nuevo_ticket} REGISTRADO CORRECTAMENTE")
        print("=" * 60)

        print(f"Fecha                : {fecha_reporte}")
        print(f"Horario              : {horario_registro}")
        print(f"Categoría            : {categoria}")
        print(f"Área                 : {area}")

        print("-" * 60)

        print(f"Prioridad IA         : {prioridad_calculada}")
        print(f"Tiempo estimado IA   : {tiempo_estimado} minutos")

        print("-" * 60)

        print(f"ACCION RECOMENDADA PARA EQUIPO DE SOPORTE: {accion_inicial_soporte} ")
        print(f"\nRECOMENDACIÓN AL USUARIO MIENTRAS ESPERA ASISTENCIA: {accion_inicial_usuario}")

        print("=" * 60 + "\n")

    except Exception as error:

        print(
            f"Ocurrió un error inesperado al registrar el ticket:\n{error}"
        )

"""**EVALUACIÓN DE LOS MODELOS**"""

prediccion_prioridad = modelo_prioridad.predict(
    X_prueba_prioridad
)

exactitud_prioridad = sklearn.metrics.accuracy_score(
    y_prueba_prioridad,
    prediccion_prioridad,
)


prediccion_tiempo = modelo_tiempo.predict(
    X_prueba_tiempo
)

error_promedio_tiempo = sklearn.metrics.mean_absolute_error(
    y_prueba_tiempo,
    prediccion_tiempo,
)

print("¡SISTEMA DOBLE ENTRENADO!")
print("=" * 60)
print(f"Exactitud del modelo de prioridad : {exactitud_prioridad:.2%}")
print(
    f"Error promedio del modelo de tiempo: {error_promedio_tiempo:.1f} minutos"
)
print("=" * 60)

"""#Menu principal"""

while True:

    print("\n=============================================")
    print("                  AI ELITE")
    print("=============================================")
    print("1. Buscar ticket")
    print("2. Registrar ticket")
    print("3. Chatbot")
    print("4. Ver patrones")
    print("5. Salir")

    opcion = input("\nSeleccione una opción: ").strip()

    if opcion == "1":

        buscar_tickets()

    elif opcion == "2":

        print("\n=============================================")
        print("        REGISTRO DE NUEVO TICKET")
        print("=============================================")

        categorias_validas = [
            "Acceso al sistema",
            "Base de datos",
            "Correo electrónico",
            "Equipo lento",
            "Hardware",
            "Impresora",
            "Internet",
            "Plataforma virtual",
            "Seguridad",
            "Software",
        ]

        areas_validas = [
            "Académica",
            "Administración",
            "Biblioteca",
            "Dirección",
            "Finanzas",
            "Laboratorio",
            "Registro",
            "Tecnología",
        ]

        usuarios_validos = [
            "Administrativo",
            "Directivo",
            "Docente",
            "Estudiante",
            "Técnico",
        ]

        dispositivos_validos = [
            "Desktop",
            "Impresora",
            "Laptop",
            "Móvil",
            "Red",
            "Router",
            "Servidor",
            "Tablet",
        ]

        urgencias_validas = [
            "Alta",
            "Media",
            "Baja",
        ]

        impactos_validas = [
            "Alto",
            "Medio",
            "Bajo",
        ]

        paso = 1

        while True:

            if paso == 1:

                print("\n[1/7] Descripción del problema")
                print("Escriba 0 para cancelar el registro.")

                descripcion = input("Describe el problema de soporte: ")

                if descripcion == "0":
                    print("\nRegistro cancelado.")
                    break

                paso = 2

            elif paso == 2:

                categoria = seleccionar_opcion(
                    "[2/7] Seleccione la categoría",
                    categorias_validas,
                )

                if categoria == "VOLVER":
                    paso = 1
                else:
                    categoria_final = categoria
                    paso = 3

            elif paso == 3:

                area = seleccionar_opcion(
                    "[3/7] Seleccione el área afectada",
                    areas_validas,
                )

                if area == "VOLVER":
                    paso = 2
                else:
                    area_final = area
                    paso = 4

            elif paso == 4:

                usuario = seleccionar_opcion(
                    "[4/7] Seleccione el tipo de usuario",
                    usuarios_validos,
                )

                if usuario == "VOLVER":
                    paso = 3
                else:
                    tipo_usuario_final = usuario
                    paso = 5

            elif paso == 5:

                dispositivo = seleccionar_opcion(
                    "[5/7] Seleccione el dispositivo",
                    dispositivos_validos,
                )

                if dispositivo == "VOLVER":
                    paso = 4
                else:
                    dispositivo_final = dispositivo
                    paso = 6

            elif paso == 6:

                urgencia = seleccionar_opcion(
                    "[6/7] Seleccione el nivel de urgencia",
                    urgencias_validas,
                )

                if urgencia == "VOLVER":
                    paso = 5
                else:
                    urgencia_final = urgencia
                    paso = 7

            elif paso == 7:

                impacto = seleccionar_opcion(
                    "[7/7] Seleccione el nivel de impacto",
                    impactos_validas,
                )

                if impacto == "VOLVER":
                    paso = 6
                else:
                    impacto_final = impacto
                    break

        if paso == 1:
            continue

        print("\n=============================================")
        print("           RESUMEN DEL TICKET")
        print("=============================================")
        print(f"Descripción : {descripcion}")
        print(f"Categoría   : {categoria_final}")
        print(f"Área        : {area_final}")
        print(f"Usuario     : {tipo_usuario_final}")
        print(f"Dispositivo : {dispositivo_final}")
        print(f"Urgencia    : {urgencia_final}")
        print(f"Impacto     : {impacto_final}")

        confirmar = input("\n¿Desea registrar este ticket? (S/N): ").strip().upper()

        if confirmar == "S":

            registrar_ticket(
                descripcion=descripcion,
                categoria=categoria_final,
                area=area_final,
                tipo_usuario=tipo_usuario_final,
                dispositivo=dispositivo_final,
                urgencia=urgencia_final,
                impacto=impacto_final,
            )

    elif opcion == "3":

        iniciar_chatbot()

    elif opcion == "4":

        while True:

            print("\n=============================================")
            print("          VISUALIZACIÓN DE PATRONES")
            print("=============================================")
            print("1. Resumen estructural del dataset")
            print("2. Patrones de solicitudes")
            print("3. Volver al menú principal")

            opcion_grafico = input("\nSeleccione una opción: ").strip()

            if opcion_grafico == "1":

                mostrar_resumen_dataset(dataset)

            elif opcion_grafico == "2":

                mostrar_patrones_dataset(dataset)

            elif opcion_grafico == "3":

                break

            else:

                print("\nOpción inválida. Intente nuevamente.")

    elif opcion == "5":

        print("\nPrograma finalizado.")
        break

    else:

        print("\nOpción inválida.")

"""#Resultados obtenidos

* Registrar solicitudes.

* Recomendacion inicial al equipo de soporte segun el caso.

* Sugerencia inicial al usuario.

* Buscar tickets.

* Analizar patrones.

* Recomendar acciones.

* Orientar al usuario mediante un chatbot.

* Predecir prioridad utilizando Machine Learning.

* Estimar automáticamente el tiempo de atención.

#Limitaciones

* El modelo depende de la calidad del dataset.

* El chatbot trabaja mediante reglas simples.

* El árbol de decisión puede mejorar utilizando más datos.

#Concideraciones eticas

* El sistema fue diseñado para apoyar la labor del personal de soporte y no para reemplazar completamente la toma de decisiones humanas.

* La información utilizada debe manejarse respetando la privacidad de los usuarios.

* Las predicciones generadas por el modelo deben considerarse recomendaciones y no decisiones definitivas.

#Conclusion
El sistema fue diseñado como una herramienta de apoyo para optimizar la gestión del personal de soporte técnico, proporcionando información relevante y facilitando la atención de incidentes, pero sin reemplazar completamente la experiencia, criterio y toma de decisiones del personal humano.

La finalidad principal del sistema es mejorar el proceso de registro, análisis y seguimiento de los casos reportados, mediante la implementación de funcionalidades inteligentes que permitan agilizar la identificación de problemas y ofrecer una respuesta inicial más eficiente. Estas soluciones incluyen la asistencia durante el registro de incidencias, la generación de sugerencias iniciales para el personal encargado del soporte y la orientación al usuario mientras espera la atención de un técnico especializado.

El chatbot funciona como un asistente integral dentro del sistema, diseñado para interactuar con los usuarios, brindar orientación básica, recopilar información relevante del incidente y facilitar el acceso a las diferentes funcionalidades disponibles. Su objetivo es servir como un primer punto de contacto que permita reducir tiempos de espera y mejorar la experiencia del usuario durante el proceso de soporte.

Durante el registro de un nuevo caso, el sistema analiza la información proporcionada por el usuario y genera estimaciones automáticas relacionadas con la prioridad del incidente y el tiempo aproximado de resolución. Estas estimaciones permiten al personal de soporte organizar mejor sus recursos, identificar los casos que requieren mayor atención y establecer una planificación más eficiente de las actividades pendientes.

Es importante destacar que las predicciones generadas por los modelos inteligentes del sistema deben ser interpretadas como recomendaciones basadas en los datos disponibles y patrones previamente analizados. Estas sugerencias no representan decisiones definitivas, ya que la evaluación final siempre dependerá del criterio del personal técnico encargado, quien podrá validar, modificar o complementar la información proporcionada por el sistema según las características particulares de cada situación.
"""